### ISSUE TITLE
Entry Points & Exclude not working

### ISSUE THREAD

**Issue by Levelheader** [SerenityEnterprises/paramorphism-issues#11]
I'm obfuscating a minecraft client. The main class is stored at net/minecraft/client/main/Main like normal, the only problem is that when I set the entry points as such, it only makes a fake Main class with no contents or method. When I try to exclude such, the main is still missing but a different class is there. Either way, I can't get it working on b0.14.

**Comment by char** [comment]
The 'fake Main class' should actually contain the methods, are you sure they're not hidden?

Do you have a log from when you tried to run the obfuscated game?

**Comment by char** [comment]
Stale issue.
