### ISSUE TITLE
Verify Exception in obfuscator-generated class

### ISSUE THREAD

**Issue by zorftw** [SerenityEnterprises/paramorphism-issues#13]
Error log:
![image](https://user-images.githubusercontent.com/19976600/54534683-2e72c280-498d-11e9-9043-2bf058b20123.png)

Remapper and almost every strategy have been disabled. When the 'noverify' argument is enabled this issue is just ignored, but the program refuses to start.

Config is as follows:
![image](https://user-images.githubusercontent.com/19976600/54534858-91fcf000-498d-11e9-8ee0-0999a27617f6.png)

Using Paramorphism version 0.14

EDIT:
After some debugging, the method which caused this issue was 'string_indirection'.
After disabling it, the program successfully executed.

**Comment by char** [comment]
Note: these `- enabled: false` lines should be `enabled: false`, but I'll look into this bug.

It's weird that the issue is coming from a FieldInsn, though.

**Comment by char** [comment]
Can you try this with Paramorphism 1.0-beta? Thanks.

**Comment by zorftw** [comment]
Issue has been resolved in the Beta version. (1.0)
