### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by rs01923** [SerenityEnterprises/paramorphism-issues#14]
I keep getting this error on any config i try:
Exception in thread "main" java.lang.VerifyError: Call to wrong <init> method

Version: 1.1-beta

Error:
https://hasteb.in/ohepixoj.sql
Config:
https://hasteb.in/podoqoxu.yaml

**Comment by char** [comment]
Can reproduce, working on a fix.

**Comment by char** [comment]
Fixed in Paramorphism `1.1-beta-hotfix`.
