### ISSUE TITLE
'Junk Signatures' strategy breaks reflection

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [SerenityEnterprises/paramorphism-issues#6]
Using junk signatures crashes when the JVM tries to call `sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature`.

This means that any call to `Class.getGenericSuperclass()` will fail, so we'll disable junk signatures by default for now.

**Comment by Retarded-Skid** [comment]
Is it `Junk` in the random garbage sense? Could you instead generate valid type signatures that wildly don't match the defined type? _(Or are similar but intentionally misleading)_

**Comment by half-cambodian-hacker-man** [comment]
@Retarded-Skid The point of the strategy is that some decompilers outright crash if they can't parse a type signature, but the JVM doesn't.

But we've found out that the JVM *does*, it's just only when using reflection.

**Comment by half-cambodian-hacker-man** [comment]
Closing. The default state of Junk Signatures will be decided by the `no-reflection` flag described in #7.
